In [1]:
import pandas as pd

In [3]:
data={
    "name" :["atharva","amogh","shllok"],
    "marks" :[12,13,14]
}
d = pd.DataFrame(data)
d

      name  marks
0  atharva     12
1    amogh     13
2   shllok     14

In [5]:
temp = [["harry",34] ,["shllok",89],["amogh",45]]
temp

[['harry', 34], ['shllok', 89], ['amogh', 45]]

In [7]:
b = pd.DataFrame(temp,columns=["name","marks"])

In [8]:
b

     name  marks
0   harry     34
1  shllok     89
2   amogh     45

In [9]:
df = pd.read_excel("data.xlsx")
df

     name School  marks
0   Arnav    PTV     45
1   Aarav   Mbbs     56
2  Chetan    MNB     58
3  Nilesh    NBH     89
4  Shllok    JIK     23

In [12]:
df = pd.read_excel("data.xlsx")

In [13]:
df

     name School  marks
0   Arnav    PTV     45
1   Aarav   Mbbs     56
2  Chetan    MNB     58
3  Nilesh    NBH     89
4  Shllok    JIK     23

In [16]:
s = pd.read_csv("data.csv")

In [17]:
s

     name School  marks
0   Arnav    PTV     45
1   Aarav   Mbbs     56
2  Chetan    MNB     58
3  Nilesh    NBH     89
4  Shllok    JIK     23