In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Temp.csv")

In [9]:
df[['Actor','IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [14]:
df.loc[0:3,'Actor']

0    Shah Rukh Khan
1       Salman Khan
2        Aamir Khan
3     Ranbir Kapoor
Name: Actor, dtype: object

In [16]:
df.iloc[0:8,0:7]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5

In [20]:
 s = df.iloc[0:4,0:6].copy()

In [22]:
s

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [27]:
df.at[0,'IMDb']

np.float64(7.2)

In [28]:
df.at[1,'Actor']

'Salman Khan'

In [32]:
df[(df['IMDb']>6) & (df['Year']>2000)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [33]:
df.query("Year>2000")['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [35]:
df.query(" Year>2010 and Actor == 'Ranveer Singh'")

           Actor       Film  Year       Genre  BoxOffice(INR Crore)  IMDb
4  Ranveer Singh  Padmaavat  2018  Historical                   585   7.0

In [38]:
df.query(" Actor=='Ranveer Singh'")['IMDb']

4    7.0
Name: IMDb, dtype: float64

In [40]:
t = 8
df.query(" IMDb > @t")['Actor']

2             Aamir Khan
5     Ayushmann Khurrana
11         Vicky Kaushal
Name: Actor, dtype: object